

FROM tiredoy/bbx-php:1.0

#COPY ./extensions /usr/local/extensions
#COPY main.sh /usr/local/main.sh
#COPY php-src-php-7.0.33 /usr/local/src

#RUN export http_proxy=127.0.0.1:1199; export https_proxy=127.0.0.1:1199
#
#
#ENV GD_DEPS libjpeg-dev libpng-dev libfreetype6-dev
#
##RUN apt-get install $GD_DEPS
###
##RUN docker-php-ext-configure gd \
##        --with-gd \
##        --with-freetype-dir=/usr/include/ \
##        --with-png-dir=/usr/include/ \
##        --with-jpeg-dir=/usr/include/ && \
##      NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
##      docker-php-ext-install -j${NPROC} gd
##
#RUN /bin/sh /usr/local/main.sh
#
##RUN yum install wget
##
##RUN wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
#sed -i  's/$releasever/6.8/g' /etc/yum.repos.d/CentOS-Base.repo
